### ISSUE TITLE
Сайт о наших налогах

### ISSUE THREAD

**Issue by russian-plan** [russian-plan/Constitution-of-Russia#3]
Приветствую всех!

Сейчас работаем с друзьями над предварительной версией сайта о наших налогах.
Планируем следующие темы:

- куда идут наши налоги
- кому идут наши налоги (пример: президентские гранты всяким СтопХамам и "Хрюшки против")
- калькулятор суммы, которые гражданин платит в год

Есть желание добавить некую социальную составляющую. Возник вопрос, есть ли у кого какие идеи насчёт этой самой социальной составляющей?

Планирую опубликовать ссылку через 5-7 дней (пока наполняем информацией и тестируем).

**Comment by M1xey** [comment]
Социальная составляющая? Типа, кто, сколько и в каких регионах получил голосов на выборах?
